#----------------------------------------------------------------------------
# Post Init
#----------------------------------------------------------------------------
# Report new configuration run
# Add packages, configuration and licenses as mandated by the powers that be.
# Report such additions
#----------------------------------------------------------------------------
# FOR THE MOMENT I SUBVERT THIS SECTION FOR:
# - Installation of AWSCLI 
#   => Might already be supplied during provisionning.
# - Compile and Install RHEL7 amazon-efs-utils 
#   => Might be better done elsewhere and placed in artifactory.
#----------------------------------------------------------------------------

- name: get initially installed aws version
  ignore_errors: yes
  command: aws --version
  register: actualAWS

- name: VRA debug aws version 
  debug: 
    var: actualAWS

- name: get aws cli from artifactory
  when: actualAWS.rc != 0 or actualAWS.stdout.find('aws-cli') == -1
  get_url: 
    url: "https://{{ artifactory_genericUrl}}/awscli-exe-linux-x86_64.zip"
    dest: "~"
    username: "{{ artifactory_username }}"
    password: "{{ artifactory_password }}"

- name: Download AWS CLI if aws not present
  when: actualAWS.rc != 0 or actualAWS.stdout.find('aws-cli') == -1
  ignore_errors: yes
  unarchive:
    src: awscli-exe-linux-x86_64.zip
    dest: .
    remote_src: yes

- name: Install AWS CLI if aws not present
  when: actualAWS.rc != 0 or actualAWS.stdout.find('aws-cli') == -1
  ignore_errors: yes
  become: yes
  command: ./aws/install

- name: get just installed aws version
  ignore_errors: yes
  command: aws --version
  register: actualAWS

- name: Make AWS CLI available to everyone
  when: actualAWS.rc != 0 or actualAWS.stdout.find('aws-cli') == -1
  become: yes
  ignore_errors: yes
  command: ln -s /usr/local/aws-cli/v2/current/bin/aws /usr/local/bin/aws
#     command: ln -s /usr/local/aws-cli/v2/current/bin/aws_completer /usr/local/bin/aws_completer
