# Install python3.8

- name: "Install python3.8"
  become: yes
  shell: |
    #!bin/bash
    yum -y install rh-python38
    bash -c 'echo "export PATH=$PATH:/opt/rh/rh-python38/root/bin" >> /etc/profile.d/custom.sh'
    source /etc/profile.d/custom.sh
