#########################################
#  Airflow config
##########################################

# Create Airflow user
- name: Create the Airflow user and Airflow home
  become: yes
  shell: |
    #!bin/bash
    useradd airflow
    mkdir /opt/airflow
    chown -R airflow:airflow /opt/airflow

# Copy Airflow config files to Airflow home
- name: Copy files to Airflow home
  become: yes
  shell: |
    #!bin/bash
    mv /tmp/airflow.cfg /opt/airflow
    mv /tmp/webserver_config.py /opt/airflow
    chown -R airflow:airflow /opt/airflow

# Install Airflow as the airflow user
- name: Install Airflow as airflow user
  become: yes
  become_user: airflow
  shell: |
    #!bin/bash
    source /etc/profile    
    CONSTRAINT_URL="/tmp/constraints-3.8.txt"
    AIRFLOW_HOME=/opt/airflow
    pip install apache-airflow --constraint "${CONSTRAINT_URL}" --user
    #echo export PATH=$PATH:/home/airflow/.local/bin >> ~/.bashrc
    bash -c 'echo "export PATH=$PATH:/home/airflow/.local/bin" >> ~/.bashrc'
    source ~/.bashrc

# Configure Airflow
- name: Configure Airflow
  become: yes
  shell: |
    #!bin/bash
    mkdir /run/airflow
    chown airflow:airflow /run/airflow
    chmod 0755 airflow -R
    # Enable airflow service
    systemctl enable airflow-scheduler
    systemctl enable airflow-webserver

# Install Kubectl
- name: Install Kubectl to be run by the airflow user
  become: yes
  become_user: airflow
  shell: |
    #!bin/bash
    cd ~
    curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/kubectl
    #wget https://artifactory.ctz.atocnet.gov.au:443/artifactory/sdp-aapiac-generic-develop-local/kubernetes/kubectl-1.21
    chmod +x ./kubectl
    mv ./kubectl $HOME/.local/bin/kubectl
    kubectl version --short --client

